name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List current directory
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configurar entorno virtual e instalar dependencias
        run: |
          python -m venv env  
          source env/bin/activate
          pip install -r lambda1/requirements.txt
          pip install -r lambda2/requirements.txt
          pip install flake8 pytest

      - name: Pruebas unitarias 
        run: |
          source env/bin/activate
          pytest

      - name: Revisión de código con flake8
        run: |
          source env/bin/activate
          flake8 lambda1/parcial.py || true
          flake8 lambda2/procesador.py || true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Forzar uso de credenciales en entorno
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}

      - name: Desplegar Lambda obtener pagina
        run: |
          cd lambda1
          source ../env/bin/activate
          zappa update

      - name: Desplegar Lambda procesar pagina
        run: |
          cd lambda2
          source ../env/bin/activate
          zappa update
